version: "3.9"  # optional since v1.27.0
services:
  web:
    build: .
    environment:
      - MONGO_URI=mongodb://mongo
    ports:
      - "80:80"
    volumes:
      - uploadcenter:/data
      - logvolume:/var/log
    links:
      - "mongo:mongo"
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - dbvolume:/data/db
volumes:
  dbvolume: {}
  uploadcenter: {}
  logvolume: {}
